language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "4"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - JAVA_HOME=/usr/lib/jvm/java-9-oracle
matrix:
  exclude:
  - env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
    node_js: "6"
  - env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
    node_js: "5"
  allow_failures:
    - env: JAVA_HOME=/usr/lib/jvm/java-9-oracle
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
      - g++-4.8
before_install:
  - npm install -g node-gyp
install:
  - npm install
before_script:
  - npm install -g gulp
script: npm test
after_success: npm run coverage
