language: node_js
sudo: false
node_js:
  - "5"
  - "4"
addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
install:
  - npm install
before_script:
  - npm install -g gulp
script: gulp test
