branches:
  except:
    - gh-pages

environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    GITHUB_API_USERNAME: abrobston
    GITHUB_API_PASSWORD:
      secure: n00Pw0lfVdSJjCOVrIEaDJF4tenjfN/6GrXmUTuYuaNiJIotoH3pasVJ8Foqel6P
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install

build: off

test_script:
  - npm test

on_success:
  - npm run coverage
